POSTGRES_USER: "postgres"
POSTGRES_PASSWORD: "postgres"
POSTGRES_DB: "postgres"
POSTGRES_HOST: "127.0.0.1"
POSTGRES_PORT: 5432

token:
  ACCESS_SECRET: "jdnfksdmfksd"
  REFRESN_SECRET: "mcmvmkmsdnfsdmfdsjf"